export const projects = [
    {
        title: 'Node Nation',
        description: "Using React, Node.js, Express & MongoDB you'll learn how to build a Full Stack MERN Application - from start to finish. The App is called Memories and it is a simple social media app that allows users to post interesting events that happened in their lives.",
          image: '/images/1.png',
          tags: ['Mongo', 'Express', 'React', 'Node'],
        source: 'https://google.com',
        visit: 'https://google.com',
        id: 0,
    },
    {
        title: 'Cats4Life',
        description: "Using React, Node.js, Express & MongoDB you'll learn how to build a Full Stack MERN Application - from start to finish. The App is called Memories and it is a simple social media app that allows users to post interesting events that happened in their lives.",
          image: '/images/1.png',
          tags: ['React', 'API'],
        source: 'https://google.com',
        visit: 'https://google.com',
        id: 1,
    },
    // {
    //     title: 'Node Nation',
    //     description: "Using React, Node.js, Express & MongoDB you'll learn how to build a Full Stack MERN Application - from start to finish. The App is called Memories and it is a simple social media app that allows users to post interesting events that happened in their lives.",
    //       image: '/images/1.png',
    //       tags: ['Mongo', 'Express', 'React', 'Node'],
    //     source: 'https://google.com',
    //     visit: 'https://google.com',
    //     id: 3,
    // },
    // {
    //     title: 'Node Nation',
    //     description: "Using React, Node.js, Express & MongoDB you'll learn how to build a Full Stack MERN Application - from start to finish. The App is called Memories and it is a simple social media app that allows users to post interesting events that happened in their lives.",
    //       image: '/images/1.png',
    //       tags: ['Mongo', 'Express', 'React', 'Node'],
    //     source: 'https://google.com',
    //     visit: 'https://google.com',
    //     id: 4,
    // },    
]